In [21]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [23]:
from nltk.corpus import stopwords
stop=stopwords.words ("english")

In [28]:
stop

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosotros',
 'vosotras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestro',
 'vuestra',
 'vuestros',
 'vuestras',
 'esos',
 'esas',
 'estoy',
 'estás',
 'está',
 'estamos',
 'estáis',
 'están',
 'esté',
 'estés',
 'estemos',
 'estéis',
 'estén',
 'estaré',
 'estarás',
 'estará',
 'estaremos',
 'estaréis',
 'estarán',
 'estaría',
 'estarías',
 'estaríamos',
 'estaríais',
 'estarían',
 'estaba',
 'estabas',
 'estábamos',
 'estabais',
 'estaban',
 'estuve',
 'estuviste',
 'estuvo',
 'estuvimos',
 'estuvisteis',
 'estuvieron',
 'estuviera',
 'estuvieras',
 'estuviéramos',
 'estuvierais',
 'estuvieran',
 'estuviese',
 'estuvieses',
 'estuviésemos',
 'estuvieseis',
 'estuviesen',
 'estando',
 'estado',
 'estada',
 'estados',
 'estadas',
 'estad',
 'he',
 'has',
 'ha',
 'hemos',
 'habéis',
 'han',
 'haya',
 'hayas',
 'hayamos',
 'hayáis',
 'hayan',
 'habré',
 'habrás',
 'habrá',
 'habremos',
 'habréis',
 'habrán',
 'habría',
 'habrías',
 'habríamos',
 'habríais',
 'habrían',
 'había',
 'habías',
 'habíamos',
 'habíais',
 'habían',
 'hube',
 'hubiste',
 'hubo',
 'hubimos',
 'hubisteis',
 'hubieron',
 'hubiera',
 'hubieras',
 'hubiéramos',
 'hubierais',
 'hubieran',
 'hubiese',
 'hubieses',
 'hubiésemos',
 'hubieseis',
 'hubiesen',
 'habiendo',
 'habido',
 'habida',
 'habidos',
 'habidas',
 'soy',
 'eres',
 'es',
 'somos',
 'sois',
 'son',
 'sea',
 'seas',
 'seamos',
 'seáis',
 'sean',
 'seré',
 'serás',
 'será',
 'seremos',
 'seréis',
 'serán',
 'sería',
 'serías',
 'seríamos',
 'seríais',
 'serían',
 'era',
 'eras',
 'éramos',
 'erais',
 'eran',
 'fui',
 'fuiste',
 'fue',
 'fuimos',
 'fuisteis',
 'fueron',
 'fuera',
 'fueras',
 'fuéramos',
 'fuerais',
 'fueran',
 'fuese',
 'fueses',
 'fuésemos',
 'fueseis',
 'fuesen',
 'sintiendo',
 'sentido',
 'sentida',
 'sentidos',
 'sentidas',
 'siente',
 'sentid',
 'tengo',
 'tienes',
 'tiene',
 'tenemos',
 'tenéis',
 'tienen',
 'tenga',
 'tengas',
 'tengamos',
 'tengáis',
 'tengan',
 'tendré',
 'tendrás',
 'tendrá',
 'tendremos',
 'tendréis',
 'tendrán',
 'tendría',
 'tendrías',
 'tendríamos',
 'tendríais',
 'tendrían',
 'tenía',
 'tenías',
 'teníamos',
 'teníais',
 'tenían',
 'tuve',
 'tuviste',
 'tuvo',
 'tuvimos',
 'tuvisteis',
 'tuvieron',
 'tuviera',
 'tuvieras',
 'tuviéramos',
 'tuvierais',
 'tuvieran',
 'tuviese',
 'tuvieses',
 'tuviésemos',
 'tuvieseis',
 'tuviesen',
 'teniendo',
 'tenido',
 'tenida',
 'tenidos',
 'tenidas',
 'tened']

In [26]:
from nltk.corpus import stopwords
stop=stopwords.words ("spanish")

In [27]:
stop

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosotros',
 'vosotras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestro',
 'vuestra',
 'vuestros',
 'vuestras',
 'esos',
 'esas',
 'estoy',
 'estás',
 'está',
 'estamos',
 'estáis',
 'están',
 'esté',
 'estés',
 'estemos',
 'estéis',
 'estén',
 'estaré',
 'estarás',
 'estará',
 'estaremos',
 'estaréis',
 'estarán',
 'estaría',
 'estarías',
 'estaríamos',
 'estaríais',
 'estarían',
 'estaba',
 'estabas',
 'estábamos',
 'estabais',
 'estaban',
 'estuve',
 'estuviste',
 'estuvo',
 'estuvimos',
 'estuvisteis',
 'estuvieron',
 'estuviera',
 'estuvieras',
 'estuviéramos',
 'estuvierais',
 'estuvieran',
 'estuviese',
 'estuvieses',
 'estuviésemos',
 'estuvieseis',
 'estuviesen',
 'estando',
 'estado',
 'estada',
 'estados',
 'estadas',
 'estad',
 'he',
 'has',
 'ha',
 'hemos',
 'habéis',
 'han',
 'haya',
 'hayas',
 'hayamos',
 'hayáis',
 'hayan',
 'habré',
 'habrás',
 'habrá',
 'habremos',
 'habréis',
 'habrán',
 'habría',
 'habrías',
 'habríamos',
 'habríais',
 'habrían',
 'había',
 'habías',
 'habíamos',
 'habíais',
 'habían',
 'hube',
 'hubiste',
 'hubo',
 'hubimos',
 'hubisteis',
 'hubieron',
 'hubiera',
 'hubieras',
 'hubiéramos',
 'hubierais',
 'hubieran',
 'hubiese',
 'hubieses',
 'hubiésemos',
 'hubieseis',
 'hubiesen',
 'habiendo',
 'habido',
 'habida',
 'habidos',
 'habidas',
 'soy',
 'eres',
 'es',
 'somos',
 'sois',
 'son',
 'sea',
 'seas',
 'seamos',
 'seáis',
 'sean',
 'seré',
 'serás',
 'será',
 'seremos',
 'seréis',
 'serán',
 'sería',
 'serías',
 'seríamos',
 'seríais',
 'serían',
 'era',
 'eras',
 'éramos',
 'erais',
 'eran',
 'fui',
 'fuiste',
 'fue',
 'fuimos',
 'fuisteis',
 'fueron',
 'fuera',
 'fueras',
 'fuéramos',
 'fuerais',
 'fueran',
 'fuese',
 'fueses',
 'fuésemos',
 'fueseis',
 'fuesen',
 'sintiendo',
 'sentido',
 'sentida',
 'sentidos',
 'sentidas',
 'siente',
 'sentid',
 'tengo',
 'tienes',
 'tiene',
 'tenemos',
 'tenéis',
 'tienen',
 'tenga',
 'tengas',
 'tengamos',
 'tengáis',
 'tengan',
 'tendré',
 'tendrás',
 'tendrá',
 'tendremos',
 'tendréis',
 'tendrán',
 'tendría',
 'tendrías',
 'tendríamos',
 'tendríais',
 'tendrían',
 'tenía',
 'tenías',
 'teníamos',
 'teníais',
 'tenían',
 'tuve',
 'tuviste',
 'tuvo',
 'tuvimos',
 'tuvisteis',
 'tuvieron',
 'tuviera',
 'tuvieras',
 'tuviéramos',
 'tuvierais',
 'tuvieran',
 'tuviese',
 'tuvieses',
 'tuviésemos',
 'tuvieseis',
 'tuviesen',
 'teniendo',
 'tenido',
 'tenida',
 'tenidos',
 'tenidas',
 'tened']

In [7]:
!pip install huggingface_hub

Collecting huggingface_hub
  Downloading huggingface_hub-2.3.0-py3-none-any.whl.metadata (16 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface_hub)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (2024.3.1)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface_hub)
  Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface_hub)
  Downloading httpx2-2.16.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging>=20.9 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (6.0.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (4.66.4)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\user\anaconda3\lib\site-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio>=4.10 in c:\users\user\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (4.15.1)
Collecting httpcore2==2.16.0 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading httpcore2-2.16.0-py3-none-any.whl.metadata (27 kB)
Collecting idna>=3.18 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading truststore-0.10.5-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: h11>=0.16 in c:\users\user\anaconda3\lib\site-packages (from httpcore2==2.16.0->httpx2<3,>=2.0.0->huggingface_hub) (0.16.0)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Downloading huggingface_hub-2.3.0-py3-none-any.whl (855 kB)
   ---------------------------------------- 0.0/855.2 kB ? eta -:--:--
   --- ------------------------------------ 81.9/855.2 kB 2.3 MB/s eta 0:00:01
   --------- ------------------------------ 194.6/855.2 kB 3.0 MB/s eta 0:00:01
   --------------- ------------------------ 327.7/855.2 kB 2.5 MB/s eta 0:00:01
   -------------------- ------------------- 440.3/855.2 kB 2.5 MB/s eta 0:00:01
   ------------------------ --------------- 532.5/855.2 kB 2.4 MB/s eta 0:00:01
   ----------------------------- ---------- 634.9/855.2 kB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 778.2/855.2 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------  849.9/855.2 kB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 855.2/855.2 kB 2.3 MB/s eta 0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.3 kB ? eta -:--:--
   -------------------------- ------------- 81.9/125.3 kB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 125.3/125.3 kB 1.9 MB/s eta 0:00:00
Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
    --------------------------------------- 0.1/3.8 MB 2.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.2/3.8 MB 2.5 MB/s eta 0:00:02
   --- ------------------------------------ 0.3/3.8 MB 2.5 MB/s eta 0:00:02
   ---- ----------------------------------- 0.4/3.8 MB 2.4 MB/s eta 0:00:02
   ----- ---------------------------------- 0.5/3.8 MB 2.4 MB/s eta 0:00:02
   ------ --------------------------------- 0.6/3.8 MB 2.5 MB/s eta 0:00:02
   ------- -------------------------------- 0.7/3.8 MB 2.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.8/3.8 MB 2.4 MB/s eta 0:00:02
   --------- ------------------------------ 0.9/3.8 MB 2.4 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/3.8 MB 2.4 MB/s eta 0:00:02
   ----------- ---------------------------- 1.1/3.8 MB 2.4 MB/s eta 0:00:02
   ------------ --------------------------- 1.2/3.8 MB 2.4 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/3.8 MB 2.4 MB/s eta 0:00:02
   -------------- ------------------------- 1.4/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------- ----------------------- 1.5/3.8 MB 2.4 MB/s eta 0:00:01
   ----------------- ---------------------- 1.6/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------ --------------------- 1.7/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.8/3.8 MB 2.4 MB/s eta 0:00:01
   -------------------- ------------------- 1.9/3.8 MB 2.4 MB/s eta 0:00:01
   --------------------- ------------------ 2.1/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------------- ----------------- 2.2/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------------ --------------- 2.3/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------------- -------------- 2.4/3.8 MB 2.4 MB/s eta 0:00:01
   -------------------------- ------------- 2.5/3.8 MB 2.4 MB/s eta 0:00:01
   --------------------------- ------------ 2.7/3.8 MB 2.4 MB/s eta 0:00:01
   ----------------------------- ---------- 2.8/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 3.0/3.8 MB 2.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.2/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 3.3/3.8 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.5/3.8 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 3.6/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  3.7/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  3.8/3.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 2.3 MB/s eta 0:00:00
Downloading httpx2-2.16.0-py3-none-any.whl (97 kB)
   ---------------------------------------- 0.0/97.9 kB ? eta -:--:--
   ------------ --------------------------- 30.7/97.9 kB ? eta -:--:--
   ---------------------------------------- 97.9/97.9 kB 5.5 MB/s eta 0:00:00
Downloading httpcore2-2.16.0-py3-none-any.whl (85 kB)
   ---------------------------------------- 0.0/85.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/85.1 kB ? eta -:--:--
   ---------------------------------------- 85.1/85.1 kB 4.7 MB/s eta 0:00:00
Downloading idna-3.20-py3-none-any.whl (69 kB)
   ---------------------------------------- 0.0/69.6 kB ? eta -:--:--
   ---------------------------------------- 69.6/69.6 kB 1.9 MB/s eta 0:00:00
Downloading truststore-0.10.5-py3-none-any.whl (19 kB)
Installing collected packages: truststore, idna, hf-xet, click, httpcore2, httpx2, huggingface_hub
  Attempting uninstall: truststore
    Found existing installation: truststore 0.8.0
    Uninstalling truststore-0.8.0:
      Successfully uninstalled truststore-0.8.0
  Attempting uninstall: idna
    Found existing installation: idna 3.7
    Uninstalling idna-3.7:
      Successfully uninstalled idna-3.7
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
Successfully installed click-8.5.0 hf-xet-1.7.0 httpcore2-2.16.0 httpx2-2.16.0 huggingface_hub-2.3.0 idna-3.20 truststore-0.10.5

In [13]:
import pandas as pd
df1 = pd.read_csv("hf://datasets/Paul/hatecheck-spanish/test.csv")
df2= pd.read_csv("hf://datasets/NoisyHate/Noisy_Hate_Data/toxic detection model test set with perturbations.csv")
df3= pd.read_csv("hf://datasets/ctoraman/large-scale-hate-speech-v1/toraman22_hate_speech_dataset_v1.tsv", sep="\t")
splits4 = {'train': 'train.csv', 'test': 'test.csv'}
df4 = pd.read_csv("hf://datasets/krishan-CSE/Davidson_Hate_Speeh_and_Emotion/" + splits4["train"])
df5 = pd.read_csv("hf://datasets/sakren/twitter_racism_dataset/twitter_racism_parsed_dataset.csv")
df6 = pd.read_csv("hf://datasets/Sowmipriya/racism/racism_text - Sheet1.csv")
df7 = pd.read_parquet("hf://datasets/ucberkeley-dlab/measuring-hate-speech/data/train-00000-of-00001.parquet")

In [32]:
df1['stopwords'] = df1['test_case'].apply(lambda x: len([x for x in
x.split() if x in stop]))
df1[['test_case','stopwords']].head()

               test_case  stopwords
0     Odio a los negros.          2
1       Odio a los gays.          2
2      Odio a los trans.          2
3  Odio a los indígenas.          2
4     Odio a los judíos.          2

In [35]:
df1['upper'] = df1['test_case'].apply(lambda x: len([x for x in x.split()
if x.isupper()]))
df1[['test_case','upper']].head()

               test_case  upper
0     Odio a los negros.      0
1       Odio a los gays.      0
2      Odio a los trans.      0
3  Odio a los indígenas.      0
4     Odio a los judíos.      0

In [38]:
from nltk.corpus import stopwords
stop = stopwords.words('spanish')
df1['test_case'] = df1['test_case'].apply(lambda x: " ".join(x for x in
x.split() if x not in stop))
df1['test_case'].head()

0       Odio negros.
1         Odio gays.
2        Odio trans.
3    Odio indígenas.
4       Odio judíos.
Name: test_case, dtype: object

In [40]:
freq = pd.Series(' '.join(df1['test_case']).split()).value_counts()[:10]
freq

Los               547
No                319
trans             275
judíos            231
discapacitados    231
negros            231
gays              231
indígenas         231
ser               230
mujeres           223
Name: count, dtype: int64

In [41]:
freq = pd.Series(' '.join(df1['test_case']).split()).value_counts()[:-10]
freq

Los               547
No                319
trans             275
judíos            231
discapacitados    231
                 ...
putas.              1
subnormales.        1
retrasados.         1
mogólicos.          1
indios.             1
Name: count, Length: 1651, dtype: int64

In [42]:
!pip install -U textblob

Collecting textblob
  Downloading textblob-0.20.1-py3-none-any.whl.metadata (4.0 kB)
Collecting nltk>=3.9 (from textblob)
  Downloading nltk-3.10.4-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (0.7.1)
Requirement already satisfied: click in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.5.0)
Requirement already satisfied: joblib in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.66.4)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from tqdm->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.20.1-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ----- ---------------------------------- 81.9/625.0 kB 4.8 MB/s eta 0:00:01
   ------------ --------------------------- 194.6/625.0 kB 3.0 MB/s eta 0:00:01
   ------------------- -------------------- 307.2/625.0 kB 2.7 MB/s eta 0:00:01
   ---------------------------- ----------- 440.3/625.0 kB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 522.2/625.0 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------  624.6/625.0 kB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 625.0/625.0 kB 2.3 MB/s eta 0:00:00
Downloading nltk-3.10.4-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.7 MB 3.0 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.7 MB 2.8 MB/s eta 0:00:01
   ------- -------------------------------- 0.3/1.7 MB 2.5 MB/s eta 0:00:01
   --------- ------------------------------ 0.4/1.7 MB 2.5 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.7 MB 2.3 MB/s eta 0:00:01
   ------------ --------------------------- 0.6/1.7 MB 2.5 MB/s eta 0:00:01
   --------------- ------------------------ 0.7/1.7 MB 2.5 MB/s eta 0:00:01
   ----------------- ---------------------- 0.8/1.7 MB 2.4 MB/s eta 0:00:01
   ------------------- -------------------- 0.8/1.7 MB 2.4 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.7 MB 2.4 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.7 MB 2.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.1/1.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------- ----------- 1.2/1.7 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 1.4/1.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 1.5/1.7 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 1.6/1.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  1.7/1.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 2.4 MB/s eta 0:00:00
Installing collected packages: nltk, textblob
  Attempting uninstall: nltk
    Found existing installation: nltk 3.8.1
    Uninstalling nltk-3.8.1:
      Successfully uninstalled nltk-3.8.1
Successfully installed nltk-3.10.4 textblob-0.20.1

In [43]:
from textblob import TextBlob
df1['test_case'][:5].apply(lambda x: str(TextBlob(x).correct()))

0      Dio negroes.
1         Dio days.
2        Dio trans.
3    Dio indígenas.
4       Dio judges.
Name: test_case, dtype: object

In [45]:
nltk.download('punkt')
TextBlob(df1['test_case'][1]).words

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

WordList(['Odio', 'gays'])

In [14]:
df1

,mhc_case_id,functionality,test_case,label_gold,target_ident,ref_case_id,ref_templ_id,templ_id,case_templ,gender_male,gender_female,label_annotated,label_annotated_maj,disagreement_in_case,disagreement_in_template
0,spanish-1,derog_neg_emote_h,Odio a los negros.,hateful,black people,NaN,NaN,1,NaN,Odio a los [male_IDENT_P].,Odio a las [female_IDENT_P].,"['hateful', 'hateful', 'hateful']",hateful,False,False
1,spanish-2,derog_neg_emote_h,Odio a los gays.,hateful,gay people,NaN,NaN,1,NaN,Odio a los [male_IDENT_P].,Odio a las [female_IDENT_P].,"['hateful', 'hateful', 'hateful']",hateful,False,False
2,spanish-3,derog_neg_emote_h,Odio a los trans.,hateful,trans people,NaN,NaN,1,NaN,Odio a los [male_IDENT_P].,Odio a las [female_IDENT_P].,"['hateful', 'hateful', 'hateful']",hateful,False,False
3,spanish-4,derog_neg_emote_h,Odio a los indígenas.,hateful,indigenous people,NaN,NaN,1,NaN,Odio a los [male_IDENT_P].,Odio a las [female_IDENT_P].,"['hateful', 'hateful', 'hateful']",hateful,False,False
4,spanish-5,derog_neg_emote_h,Odio a los judíos.,hateful,jews,NaN,NaN,1,NaN,Odio a los [male_IDENT_P].,Odio a las [female_IDENT_P].,"['hateful', 'hateful', 'hateful']",hateful,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3740,spanish-3741,spell_leet_h,Los trans son todos unos idio7as totales.,hateful,trans people,1096.0,256.0,866,NaN,Los [male_IDENT_P] son todos unos idio7as tota...,Las [female_IDENT_P] son todas unas idio7as to...,"['hateful', 'hateful', 'hateful']",hateful,False,False
3741,spanish-3742,spell_leet_h,Los indígenas son todos unos idio7as totales.,hateful,indigenous people,1097.0,256.0,866,NaN,Los [male_IDENT_P] son todos unos idio7as tota...,Las [female_IDENT_P] son todas unas idio7as to...,"['hateful', 'hateful', 'hateful']",hateful,False,False
3742,spanish-3743,spell_leet_h,Los judíos son todos unos idio7as totales.,hateful,jews,1098.0,256.0,866,NaN,Los [male_IDENT_P] son todos unos idio7as tota...,Las [female_IDENT_P] son todas unas idio7as to...,"['hateful', 'hateful', 'hateful']",hateful,False,False
3743,spanish-3744,spell_leet_h,Los discapacitados son todos unos idio7as tota...,hateful,disabled people,1099.0,256.0,866,NaN,Los [male_IDENT_P] son todos unos idio7as tota...,Las [female_IDENT_P] son todas unas idio7as to...,"['hateful', 'hateful', 'hateful']",hateful,False,False
3744,spanish-3745,spell_leet_h,Las mujeres son todas unas idio7as totales.,hateful,women,1100.0,256.0,866,NaN,Los [male_IDENT_P] son todos unos idio7as tota...,Las [female_IDENT_P] son todas unas idio7as to...,"['hateful', 'hateful', 'hateful']",hateful,False,False

In [15]:
df2

,created_date,funny,wow,sad,likes,disagree,toxicity,severe_toxicity,obscene,sexual_explicit,...,other_race_or_ethnicity,physical_disability,intellectual_or_learning_disabil,psychiatric_or_mental_illness,other_disability,identity_annotator_count,toxicity_annotator_count,clean_version,perturbed_version,quality_mean
0,2016-02-12 21:30:11.686130+00,0.0,0.0,0.0,0.0,0.0,0.700000,0.100000,0.700000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,this is pretty much exactly how i feel damn,this is pretty much exactly how i feel daaammnn,4.000000
1,2016-02-23 22:20:02.065242+00,0.0,0.0,0.0,0.0,0.0,0.728571,0.014286,0.242857,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,70.0,this kind of crap will end when trump is presi...,this kind of crapp will end when trump is pres...,3.750000
2,2016-03-09 21:21:51.801170+00,0.0,0.0,0.0,1.0,0.0,0.610169,0.000000,0.016949,0.016949,...,0.0,0.0,0.0,0.0,0.0,4.0,59.0,amy miller is a very terrible person,amy miller is a very teeeerrrrible person,4.200000
3,2016-03-12 01:50:08.580449+00,0.0,0.0,0.0,0.0,0.0,0.938776,0.000000,0.163265,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,49.0,you sir are an idiot,you sir are an IDOT,3.400000
4,2016-03-14 15:55:37.857710+00,0.0,0.0,0.0,0.0,0.0,0.800000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.8,0.0,10.0,5.0,indeed liberal dementia is a social disease a ...,indeed libral dementia is a social disease a m...,3.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334,2017-11-10 15:41:26.381013+00,0.0,1.0,0.0,0.0,0.0,0.718310,0.042254,0.014085,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,71.0,prepare to be burned all those who venture there,prepare to be bUrnEd all those who venture there,3.666667
1335,2017-11-10 15:51:43.939360+00,0.0,0.0,0.0,0.0,2.0,0.833333,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,how un informed and ignorant,how un informed and IGNorant,3.600000
1336,2017-11-10 17:33:49.248702+00,0.0,0.0,0.0,1.0,0.0,0.628571,0.000000,0.042857,0.014286,...,0.0,0.0,0.0,0.0,0.0,0.0,70.0,did he own anyone else then shut up,did he own anyone else then Shìt up,3.600000
1337,2017-11-10 19:55:57.525853+00,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.200000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,your hypocrisy is showing too,your hypcrisy is showing too,3.600000
1338,2017-11-10 20:59:29.650862+00,0.0,0.0,0.0,1.0,1.0,0.900000,0.100000,0.900000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,10.0,here we go again damned with no realistically ...,here we go again dammned with no realistically...,3.500000

In [16]:
df3

,TweetID,LangID,TopicID,Label_1,Label_2,Label_3,Label_4,Label_5,HateLabel
0,1377203834410434562,1,0,0,2,2,1,2,2
1,1344559711102906368,1,0,2,1,2,2,1,2
2,1278008664373297159,1,0,2,1,0,1,0,2
3,1277564191826522112,1,0,2,1,2,0,1,2
4,1277585299632123904,1,0,0,0,2,1,2,2
...,...,...,...,...,...,...,...,...,...
99995,1377057153429684225,1,4,0,0,0,0,0,0
99996,1375630921089474560,1,4,0,0,0,1,0,0
99997,1376859346190098441,1,4,0,0,0,0,0,0
99998,1277971254947885057,1,4,0,0,0,0,0,0
99999,1343713003506696192,1,4,0,0,0,0,0,0

In [17]:
df4

,text,labels,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,oh I forgot you retarded lol lemme break it do...,0,0.460740,0.075613,0.375869,0.016227,0.956006,0.055314,0.226038,0.011040,0.040101,0.183850,0.019955
1,Otw to DC. Hopefully I'll see my best bitch . ...,0,0.074913,0.457267,0.045327,0.010142,0.964258,0.053902,0.773113,0.008859,0.014811,0.075721,0.100954
2,Bitches dont wann fxck me no more bitches wann...,0,0.983197,0.028741,0.920244,0.021525,0.031499,0.008084,0.016446,0.035104,0.161632,0.012501,0.007640
3,The paranoid fear of sharia on the right boils...,0,0.586907,0.067405,0.629855,0.960799,0.010082,0.005313,0.037484,0.099481,0.113589,0.019648,0.013102
4,Damn hoe.. You so ugly even hello kitty said g...,1,0.980648,0.027721,0.934816,0.020831,0.029153,0.006031,0.014789,0.047396,0.255515,0.012861,0.005897
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18581,Would you be interested in some eggplant? : tw...,0,0.021793,0.798481,0.028151,0.021047,0.874772,0.095868,0.257052,0.018958,0.026513,0.256295,0.146228
18582,Mad respect to Affleck for refusing to wear a ...,0,0.971895,0.024625,0.906526,0.011215,0.043293,0.008427,0.014036,0.057052,0.412615,0.013722,0.005857
18583,So ike just had to punch a nigga for harassing...,0,0.983925,0.034807,0.943740,0.031224,0.026861,0.006441,0.013377,0.036613,0.157053,0.019073,0.006962
18584,Talking shit like a hoe about huh so like a ma...,0,0.983667,0.030258,0.923250,0.028771,0.026041,0.007383,0.016235,0.034846,0.143701,0.013043,0.007830
18585,same here. Fucking hated that bitch.,0,0.983467,0.026987,0.941109,0.045305,0.020232,0.007247,0.011968,0.038455,0.175781,0.015719,0.007014

In [18]:
df5

,index,id,Text,Annotation,oh_label
0,5.767493e+17,5.767493e+17,@AAlwuhaib1977 Muslim mob violence against Hin...,racism,1
1,5.408905e+17,5.408905e+17,@Te4m_NiGhtM4Re http://t.co/5Ih7MkDbQG,none,0
2,5.678433e+17,5.678433e+17,@jncatron @isra_jourisra @AMPalestine Islamoph...,racism,1
3,5.766462e+17,5.766462e+17,"Finally I'm all caught up, and that sudden dea...",none,0
4,5.713492e+17,5.713492e+17,@carolinesinders @herecomesfran *hugs*,none,0
...,...,...,...,...,...
13466,5.755964e+17,5.755964e+17,#mkr NOOOOO!!! I wanted Kat and Andre to lose!!!,none,0
13467,5.580631e+17,5.580631e+17,RT @MumtazCeltik: @WhiteHouse @VP \n\n#Kobane ...,none,0
13468,5.755969e+17,5.755969e+17,Glad the proper competition is starting and ev...,none,0
13469,5.755990e+17,5.755990e+17,"No worries Pete and Manu, take all the time of...",none,0
13470,5.755977e+17,5.755977e+17,@mykitchenrules #mkr please kick off that lady...,none,0

In [19]:
df6

      Unnamed: 0                                       text_content  is_racist
0              0                  😆third worlder Indian 🇮🇳No thanks          1
1              1  😂😂nobody but African drug dealers,looters and ...          1
2              2  … so an outsider, even being a communist inbre...          0
3              3  “Jewface”…gonna have to remember that one. Tha...          1
4              4     you can take the coloreds out of the ghetto...          1
...          ...                                                ...        ...
2453        2453  yep you can go back to your home land and find...          1
2454        2454                              a giant murder wave !          0
2455        2455  Those types of immigrants aren’t even good eno...          0
2456        2456  Oh wow! Are the 'chinese military males' in ca...          1
2457        2457                        Barack Husein Obama = satan          0

[2458 rows x 3 columns]

In [20]:
df7

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,annotator_religion_hindu,annotator_religion_jewish,annotator_religion_mormon,annotator_religion_muslim,annotator_religion_nothing,annotator_religion_other,annotator_sexuality_bisexual,annotator_sexuality_gay,annotator_sexuality_straight,annotator_sexuality_other
0,47777,10873,3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,39773,2790,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
2,47101,3379,3,4.0,4.0,4.0,4.0,4.0,4.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,43625,7365,3,2.0,3.0,2.0,1.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
4,12538,488,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135551,37080,8590,2,1.0,1.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
135552,22986,8303,2,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,True,True,False,False,False
135553,21008,6207,2,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
135554,22986,7886,2,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,True,False,False,False,True,False
135555,14785,6897,0,4.0,4.0,4.0,2.0,2.0,2.0,3.0,...,False,False,False,False,False,False,False,False,True,False